<?php 
namespace backend\controllers;
/*
use backend\models\SUser;
use common\models\Actions;
use common\models\Orders;
use common\models\User;
use common\models\OrdersPay;
*/
use frontend\components\MainController;


use yii\web\Response;

class ApiController extends MainController
{
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'view' => '//site/error'
            ],
            'cart' => [
                'class' => 'frontend\components\CartAction',
            ],
        ];
    }

	/*
	*	Первичная оценка доставки без создания заявки.
	*	https://yandex.ru/dev/taxi/doc/cargo-api/ref/v1/estimate.html
	*	Класс автомобиля для доставки (courier, express, cargo)
	*
	*  skip_door_to_door - В случае true — курьер доставит заказ только на улицу, до подъезда
	*/
	public function actionAssessmentyandex()
    {   
		$pickselect = \Yii::$app->request->post('pickselect');
	
		$address_settings = [
			'1' => [				
				'fullname' => 'Алматы, улица Айманова, 155',							
				'shortname' => 'улица Айманова, 155',		
				'lat'=> '76.89781',
				'lon'=> '43.231757',

				
			],
			'3' => [
				'fullname' => 'Алматы, проспект Сакена Сейфуллина, 617',
				'shortname' => 'проспект Сакена Сейфуллина, 617',
				'lat'=> '76.93376',
				'lon'=> '43.224729'
			]				
		];
	

	$longitude_from = $address_settings[$pickselect]['lat'];
		$latitude_from = $address_settings[$pickselect]['lon'];
	
	
	//	$longitude_from = \Yii::$app->request->post('longitude_from');
	//	$latitude_from = \Yii::$app->request->post('latitude_from');
		$longitude_to = \Yii::$app->request->post('longitude_to');
		$latitude_to = \Yii::$app->request->post('latitude_to');
		
		
		$pick = \Yii::$app->request->post('pick');
		$name = \Yii::$app->request->post('name');	
		

		
		
		
		/*
		$params = array(
			'geocode' => $name, // адрес
			'format'  => 'json',                          // формат ответа
			'results' => 1,                               // количество выводимых результатов
			'apikey'     => 'a800cece-8fcc-4d1c-bc91-da2061eb8d3e',                           // ваш api key
		);

		$ch = curl_init('https://geocode-maps.yandex.ru/1.x/?' . http_build_query($params, '', '&'));
						 
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_HEADER, false);
		$html = curl_exec($ch);
		curl_close($ch);  
		$html = json_decode($html);

		$coord = explode(' ', $html->response->GeoObjectCollection->featureMember[0]->GeoObject->Point->pos);
		
		*/
			// $longitude_to = \Yii::$app->request->post('longitude_to');
		// $latitude_to = \Yii::$app->request->post('latitude_to');
		
		// $longitude_to = $coord[0];
		// $latitude_to = $coord[1];
			
		$coord_answer = $latitude_to . ',' . $longitude_to . ',' . $latitude_from . ',' . $longitude_from;
			
		$params = array(
			'items' => array(
				array(
					"quantity"=> 1,
					"size"=> array(
						"height"=> 0.1,							
						"length"=> 0.1,
						"width"=> 0.1
					),
					"weight"=> 2
				)
			), 
			'requirements' => array(
				"taxi_class"=> "express"
			),
			'route_points' => array(
				array(
					'coordinates' => array(
						(double)$longitude_from, (double)$latitude_from
					)
				),
				array(
					'coordinates' => array(
						(double)$longitude_to,(double)$latitude_to
					)
				)
			),
			"skip_door_to_door"=>false
 
		);
		
		$string = json_encode($params); 		
	
		$string = json_encode($params); 
		$ch = curl_init("https://b2b.taxi.yandex.net/b2b/cargo/integration/v1/check-price");
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Content-Type: application/json',
			'Accept-Language: en-US',
			'Authorization: Bearer ' . \Yii::$app->params['bearer'],
			'Content-Length: ' . strlen($string)
		));
		curl_setopt($ch, CURLOPT_POSTFIELDS, $string); 
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($params)); 
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_HEADER, false);
		$html = curl_exec($ch);
		curl_close($ch);  
		$html = json_decode($html);
		
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'code'=>$html->price, 
			'coord_answer' => $coord_answer,
			'name' => $name,
			'pick' => $pick
        ];
    }	
}