<?php
/**
 * Created by PhpStorm.
 * Project: kingfisher
 * User: lxShaDoWxl
 * Date: 21.10.15
 * Time: 12:14
 */
namespace backend\controllers;

use common\components\Debugger as d;
use backend\AdminController;
use common\models\City;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;
use yii\web\Response;

class CityController extends AdminController
{
    public function init()
    {
        $this->model = new City();
        $controller_name = Inflector::camel2id($this->id);
        $this->url = [
            'back' => [$controller_name . '/index'],
            'control' => [$controller_name . '/control']
        ];
        $this->view->title = 'Города';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => [$controller_name . '/index'],
            'label' => 'Города'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $data['items'] = City::find()->orderBy(['name' => SORT_ASC])->all();
        return $this->render('//modules/citys', $data);
    }

    public function actionControl()
    {
        $model = new City();

        if ($id = \Yii::$app->request->get('id')) {
            $model = $model->findOne($id);

            $this->breadcrumb[] = [
                'url' => [],
                'label' => $model->name
            ];

            $model->validate();
        }

        $data['item'] = $model;

        if (!empty($model)) {
            return $this->render('//control/tabs_form', $data);
        }

        return $this->render('//site/error', ['message' => 'Такого города не существует.']);
    }

    public function actionChangeView()
    {
        $post = Yii::$app->request->post();
        $data = ['status' => 401];
        if(isset($post['id']) AND is_integer((int)$post['id'])){
            if($city = City::findOne(['id' => $post['id']])){
                $city->view = $post['view'];
                if($city->save()){
                    $data['status'] = 200;
                }
            }
        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return $data;
    }
}