<?php

namespace backend\controllers;

use backend\AdminController;
use common\models\Options;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * Class OptionsController
 * @package backend\controllers
 * @property \common\models\Options $model
 */
class OptionsController extends AdminController
{
    public $model;
    public function init()
    {
        $this->model = new Options();
        $this->url = [
            'back' => ['options/index'],
            'control' => ['options/control']
        ];
        $this->MenuActive('catalog');
        $this->view->title = 'Характеристики';
        $this->breadcrumb[] = [
            'url' => ['category/index'],
            'label' => 'Каталог',
        ];
        $this->breadcrumb[] = [
            'url' => ['options/index'],
            'label' => $this->view->title,
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $data['items'] = $this->model->find()->orderBy(['id' => SORT_DESC])->all($this->model->getDb());
//        $data['items']=
        return $this->render('index', $data);
    }
}