<?php
/**
 * Created by PhpStorm.
 * Project: morkovka
 * User: lxShaDoWxl
 * Date: 18.09.15
 * Time: 12:12
 */
namespace backend\controllers;

use backend\AdminController;
use common\models\ReviewsItem;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class ReviewsItemController extends AdminController
{
    public function init()
    {
        $this->model = new ReviewsItem();
        $controller_name = Inflector::camel2id($this->id);

        $this->url = [
            'back' => ['site/'.$controller_name],
            'control' => [$controller_name.'/control']
        ];
        $this->view->title = 'Отзывы товаров';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => ['site/'.$controller_name],
            'label' => 'Отзывы товаров'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }

}