<?php
/**
 * Created by PhpStorm.
 * Project: kingfisher
 * User: lxShaDoWxl
 * Date: 20.10.15
 * Time: 14:43
 */
namespace backend\controllers;

use backend\AdminController;
use common\models\Items;
use common\models\Sets;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class SetsController extends AdminController
{
    public function init()
    {
        $this->model = new Sets();
        $controller_name = Inflector::camel2id($this->id);
        $this->url = [
            'back' => ["$controller_name/index"],
            'control' => ["$controller_name/control"]
        ];
        $this->view->title = 'Сеты';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => ["$controller_name/index"],
            'label' => 'Сеты'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $data['items'] = Sets::find()->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('//modules/sets', $data);
    }
    public function actionAddItem($id)
    {
        if (Yii::$app->request->isAjax) {
            $item = Items::findOne($id);
            return $this->renderPartial('//modules/sets_item', ['item' => $item]);
        } else {
            return $this->goBack();
        }
    }
}