<?php
/**
 * Created by PhpStorm.
 * Project: morkovka
 * User: lxShaDoWxl
 * Date: 16.09.15
 * Time: 13:10
 */
namespace backend\controllers;

use backend\AdminController;
use backend\models\EditSettings;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class SettingsController extends AdminController
{
    public function init()
    {
        $this->model = new EditSettings();
        $this->url = [
            'back' => ['settings/control'],
            'control' => ['settings/control']
        ];
        $this->view->title = 'Настройки';
        $this->MenuActive('settings');
        $this->breadcrumb[] = [
            'url' => ['settings/control'],
            'label' => 'Настройки'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }
}