<?php

namespace backend\controllers;

use backend\AdminController;

use common\models\SpecActionCode;
use common\models\SpecActionPhone;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class SpecialActionPhoneController extends AdminController
{
    private $code;

    public function init()
    {
        $this->model = new SpecActionPhone();
        $this->code = SpecActionCode::findOne(Yii::$app->request->get('code'));
        $this->url = [
            'back' => ['special-action-phone/index', 'code' => $this->code->id],
            'control' => ['special-action-phone/control', 'code' => $this->code->id]
        ];
        $this->view->title = 'SMS Спец Акции';
        $this->MenuActive('special-action');
        $this->breadcrumb[] = [
            'url' => ['special-action/index'],
            'label' => 'Спец Акции'
        ];
        $this->breadcrumb[] = [
            'url' => ['special-action-code/index', 'action' => $this->code->spec_action_id],
            'label' => 'Коды Спец Акции'
        ];
        $this->breadcrumb[] = [
            'url' => ['special-action-phone/index', 'code' => $this->code->id],
            'label' => 'SMS Спец Акции'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin', 'senior_manager'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }

    public function actionIndex($code)
    {
        $code = intval($code);
        return $this->render('index', [
            'items' => SpecActionPhone::find()->where(['spec_action_code_id' => $code])->orderBy(['id' => SORT_DESC])->all(),
        ]);
    }
}