<?php

namespace backend\controllers;

use backend\AdminController;

use common\models\SpecActionCode;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class SpecialActionCodeController extends AdminController
{
    public function init()
    {
        $this->model = new SpecActionCode();
        $this->url = [
            'back' => ['special-action-code/index', 'action' => Yii::$app->request->get('action')],
            'control' => ['special-action-code/control', 'action' => Yii::$app->request->get('action')]
        ];
        $this->view->title = 'Коды Спец Акции';
        $this->MenuActive('special-action');
        $this->breadcrumb[] = [
            'url' => ['special-action/index'],
            'label' => 'Спец Акции'
        ];
        $this->breadcrumb[] = [
            'url' => ['special-action-code/index', 'action' => Yii::$app->request->get('action')],
            'label' => 'Коды Спец Акции'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin', 'senior_manager'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
                ],
            ],
        ];
    }

    public function actionIndex($action)
    {
        $action = intval($action);
        return $this->render('index', [
            'items' => SpecActionCode::find()->with([
                'item',
                'smsCodes'
            ])->where(['spec_action_id' => $action])->orderBy(['id' => SORT_DESC])->all(),
            'action' => $action
        ]);
    }
}