<?php
/**
 * Created by PhpStorm.
 * Project: kingfisher
 * User: lxShaDoWxl
 * Date: 01.04.16
 * Time: 17:41
 */
namespace backend\controllers;

use backend\AdminController;
use common\models\Subscriptions;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class SubscriptionsController extends AdminController
{
    public function init()
    {
        $this->model = new Subscriptions();
        $controller_name = Inflector::camel2id($this->id);
        $this->url = [
            'back' => ["$controller_name/index"],
            'control' => ["$controller_name/control"]
        ];
        $this->view->title = 'Подписчики';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => ["$controller_name/index"],
            'label' => 'Подписчики'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionExport()
    {
        $columns = [
            [
                'attribute' => 'email',
                'header' => 'E-Mail',
                'format' => 'text',
                'value' => function ($model) {
                    return ($model->email) ? $model->email : '';
                },
            ],
        ];
        \moonland\phpexcel\Excel::export([
            'fileName'=>'export_subs',
            'models' => Subscriptions::find()->orderBy(['id'=>SORT_DESC])->all(),
            'columns' => $columns,
//            'savePath' => Yii::getAlias('@frontend/tmp'),
//            'asAttachment' => false
        ]);
    }
}