<?php
/**
 * Created by PhpStorm.
 * Project: kingfisher
 * User: lxShaDoWxl
 * Date: 03.11.15
 * Time: 12:18
 */
namespace backend\controllers;

use backend\AdminController;
use common\models\TypeHandling;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class TypeHandlingController extends AdminController
{
    public function init()
    {
        $this->model = new TypeHandling();
        $controller_name = Inflector::camel2id($this->id);
        $this->url = [
            'back' => ["$controller_name/index"],
            'control' => ["$controller_name/control"]
        ];
        $this->view->title = 'Обработка';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => ['category/index'],
            'label' => 'Каталог'
        ];
        $this->breadcrumb[] = [
            'url' => ["$controller_name/index"],
            'label' => 'Обработка'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $data['items'] = TypeHandling::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('//modules/type_handling', $data);
    }
}