<?php


namespace apiking\controllers;

use apiking\components\ApiResponses;
use apiking\components\Rules\CheckApiKey;
use backend\models\SUser;
use yii\base\ActionFilter;
use yii\filters\AccessControl;
use yii\rest\ActiveController;
use yii\rest\Serializer;
use yii\web\ForbiddenHttpException;


class BaseApiController extends MainController
{
    use ApiResponses;

    public $modelClass = '';

    private static $protectedActions = [
        'index', 'view', 'delete', 'update', 'create'
    ];

    public $serializer = [
        'class' => Serializer::class,
        'collectionEnvelope' => 'data',
    ];

    private function getApiKey()
    {
        return !empty($_SERVER['HTTP_API_KEY']) ? $_SERVER['HTTP_API_KEY'] : null;
    }

    private function isAllow()
    {
        if (!$this->getApiKey()) {
            return false;
        }

        return SUser::find()->where([
            'role' => 'admin',
            'status' => 10,
            'auth_key' => $this->getApiKey()
        ])->exists();
    }

    public function beforeAction($action)
    {
        if (in_array($action->id, self::$protectedActions) && !$this->isAllow()) {
            $this->asJson($this->getErrorResponse('You are not authorized', 403));
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}