<?php
namespace common\models;
use shadow\assets\Select2Assets;
use Yii;

/**
 * This is the model class for table "banners".
 *
 * @property integer $id
 * @property string $img
 * @property string $img_mobile
 * @property string $url
 * @property integer $isVisible
 * @property integer $sort
 */
class Banners extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banners';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url'], 'required'],
            [['img'], 'required','on'=>['insert']],
            [['isVisible', 'sort'], 'integer'],
            [['sort'], 'default', 'value' => 0],
            [['isVisible'], 'default', 'value' => 1],
            ['img', 'image', 'extensions' => 'jpg, gif, png, jpeg'],
            ['img_mobile', 'image', 'extensions' => 'jpg, gif, png, jpeg'],
            [['url'], 'string', 'max' => 255],
			[['cities'], 'safe']
        ];
    }
    /**
     * @inheritdoc
     */
    public function beforeValidate()
    {
        if($this->isNewRecord){
            $this->scenario = 'insert';
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'img' => 'Изображение',
            'img_mobile' => 'Изображение для мобильных',
            'url' => 'Ссылка',
            'isVisible' => 'Видимость',
            'sort' => 'Порядок',
			'cities' => 'Города',
        ];
    }
	
	   /**
     * @return \yii\db\ActiveQuery
     */
    public function getBannersCities()
    {
        return $this->hasMany(BannersCities::className(), ['banner_id' => 'id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCities()
    {
        return $this->hasMany(City::className(), ['id' => 'city_id'])->via('bannersCities');
    }
    public function setCities($cities)
    {
        if (!is_array($cities)) {
            $cities = [];
        }
        $event_after = $this->isNewRecord ? $this::EVENT_AFTER_INSERT : $this::EVENT_AFTER_UPDATE;
        $name = 'cities';
        $this->on($event_after, function ($event) use ($name, $cities) {
            Yii::trace('start saveRelation');
            $this->saveRelation($name, $cities, $event);
        });
    }
	
    public function FormParams()
    {
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
            $this->sort = Banners::find()->count();
        }
        $result = [
            'form_action' => ['banners/save'],
            'cancel' => ['site/banners'],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => [
                        'isVisible' => [
                            'type' => 'checkbox'
                        ],
                        'url' => [],
                        'sort' => [],
                        'img' => [
                            'type' => 'img'
                        ],
                        'img_mobile' => [
                            'type' => 'img'
                        ],
                    ],
                ],
                'banners_cities' => [
                    'title' => 'Города',
                    'icon' => 'th-list',
                    'options' => [],
                    'fields' => [
                        'cities' => [
                            'title' => 'Баннер для городов:',
                            'type' => 'dropDownList',
                            'data' => City::find()->select(['name', 'id'])->indexBy('id')->column(),
                            'params' => [
                                'multiple' => true,
                            ]
                        ],
                    ]
                ]			
            ]
        ];
		
		$form_name = strtolower($this->formName());
        $view = Yii::$app->view;
        Select2Assets::register($view);
        $view->registerJs(<<<JS
$('#{$form_name}-cities').select2({
    width: '100%',
    language: 'ru'
});
JS
        );	
        return $result;
    }
    public function behaviors()
    {
        return [
            [
                'class' => '\shadow\behaviors\UploadFileBehavior',
                'attributes' => ['img','img_mobile'],
            ],
        ];
    }
}
