<?php

namespace common\models;

use shadow\assets\Select2Assets;
use shadow\plugins\datetimepicker\DateTimePicker;
use shadow\widgets\CKEditor;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Inflector;

/**
 * This is the model class for table "spec_action_codes".
 *
 * @property integer $id
 * @property string $uuid
 * @property integer $spec_action_id
 * @property integer $item_id
 * @property string $link
 * @property bool $status
 * @property string $url
 * @property integer $count
 *
 * @property Items $item
 * @property SpecActionPhone[] $smsCodes
 *
 */
class SpecActionCode extends \shadow\SActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'spec_action_codes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['uuid'], 'required'],
            [['uuid'], 'string', 'max' => 255],
            [['item_id', 'count'], 'integer'],
            [['!status'], 'safe'],
            [['status'], 'default', 'value' => 0],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'item_id' => 'Товар',
            'count' => 'Лимит',
            'status' => 'Статус',
            'url' => 'Ссылка',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(Items::className(), ['id' => 'item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmsCodes()
    {
        return $this->hasMany(SpecActionPhone::className(), ['spec_action_code_id' => 'id']);
    }

    public function getUrl()
    {
        return 'https://kingfisher.kz/promo/' . $this->uuid;
    }

    public function FormParams()
    {
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
        }

        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $fields = [

            'item_id' => [
                'title' => 'Товар',
                'type' => 'dropDownList',
                'data' => ['' => 'Не выбран'] + Items::find()->select(['name', 'id'])->indexBy('id')->column(),
            ],
            'count' => [
                'title' => 'Кол-во (0-безлимит)'
            ],

        ];
        if (!$this->isNewRecord) {
            $fields = ArrayHelper::merge($fields, [
                'url' => [
                    'type' => 'text',
                    'field_options' => [
                        'inputOptions' => [
                            'readonly' => 'readonly'
                        ]
                    ],
                    'params' => [
                        'afterInput' => function () {
                            return Html::tag('div',
                                Html::a(
                                    Html::img('https://chart.googleapis.com/chart?chs=250x250&cht=qr&chl='.$this->url.'&choe=UTF-8'),
                                    'https://chart.googleapis.com/chart?chs=250x250&cht=qr&chl='.$this->url.'&choe=UTF-8',
                                    [
                                        'target'=>'_blank'
                                    ]
                                )
                            );
                        }
                    ]
                ]
            ]);
        }
        $result = [
            'form_action' => ["$controller_name/save", 'action' => Yii::$app->request->get('action')],
            'cancel' => ["$controller_name/index", 'action' => Yii::$app->request->get('action')],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => $fields,
                ],
            ]
        ];
        $form_name = strtolower($this->formName());
        $view = Yii::$app->view;
        Select2Assets::register($view);
        $view->registerJs(<<<JS
$('#{$form_name}-item_id').select2({
    width: '100%',
    language: 'ru'
});
JS
        );
        return $result;
    }

    public function beforeValidate()
    {
        if ($this->isNewRecord) {
            $this->uuid = md5(uniqid() . '_' . time());
            $this->spec_action_id = Yii::$app->request->get('action');
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function checkValid()
    {
        $specAction = SpecActions::find()->where(['id' => $this->spec_action_id])->one();

        if ($specAction->date_end < time() || $specAction->date_start > time()) {
            return false;
        }

        if ($this->count == 0) {
            return true;
        }
        if (SpecActionPhone::find()->where([
                'spec_action_code_id' => $this->id,
                'status' => 1
            ])->count() < $this->count) {
            return true;
        }
        return false;
    }
}
