<?php
/**
 * Created by PhpStorm.
 * Project: yii2-cms
 * User: viktor
 * Date: 20.04.15
 * Time: 15:52
 */

namespace shadow\widgets;

use yii\helpers\Html;
use shadow\assets\AdminActiveFormAsset;
use yii\bootstrap\ActiveForm;
use yii\helpers\Json;
use yii\base\InvalidConfigException;

class AdminActiveForm extends ActiveForm {
    /**
     * @var string the default field class name when calling [[field()]] to create a new field.
     * @see fieldConfig
     */
    public $fieldClass = 'shadow\widgets\AdminActiveField';
	
	public function init()
    {
		if (!in_array($this->layout, ['default', 'horizontal', 'inline'])) {
            throw new InvalidConfigException('Invalid layout type: ' . $this->layout);
        }

        if ($this->layout !== 'default') {
            Html::addCssClass($this->options, 'form-' . $this->layout);
        }
		
        if (!isset($this->options['id'])) {
            $this->options['id'] = $this->getId();
        }

		$this->options['class'] = 'save';
 

		ob_start();
        ob_implicit_flush(false);		
    }
	
	// public function run()
	// {
		// if ($this->enableClientScript) {
			// $id = $this->options['id'];
			// $options = Json::encode($this->getClientOptions());
			// $attributes = Json::encode($this->attributes);
			// $view = $this->getView();
			// AdminActiveFormAsset::register($view);
			// $view->registerJs("jQuery('#$id').yiiActiveForm($attributes, $options);");
			// $this->enableClientScript = false;
		// }
		// parent::run(); // TODO: Change the autogenerated stub
	// }
	
	public function run()
	{
		
		$html = Html::beginForm($this->action, $this->method, $this->options);
		
		if ($this->enableClientScript) {
			$id = $this->options['id'];
			$options = Json::encode($this->getClientOptions());
			$attributes = Json::encode($this->attributes);
			$view = $this->getView();
			AdminActiveFormAsset::register($view);
			$view->registerJs("jQuery('#$id').yiiActiveForm($attributes, $options);");
			$this->enableClientScript = false;
		}
				
		$content = ob_get_clean();

        $html .= $content;

        $html .= Html::endForm();
        return $html;
				
	//	parent::run(); // TODO: Change the autogenerated stub
	}
	
	
}