<?php

namespace frontend\assets;

use yii\web\AssetBundle;

class WidgetCloudpaymentsAsset extends AssetBundle
{

    /**
     * @inheritdoc
     */
    public $sourcePath = '@frontend/assets/main';
    /**
     * @inheritdoc
     */
    public $js = [
        'js/plugins/widget.cloudpayments.js',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

//        $cloudpayment_domen = 'ru';
//
//        header(
//            "Content-Security-Policy: "
//            . "frame-ancestors https:; "
//            . "connect-src"
//            . " https://*.cloudpayments." . $cloudpayment_domen
//            . " https://*.yandex.ru"
//            . " https://*.google-analytics.com"
//            . " https://*.doubleclick.net"
//            . " https://*.plerdy.com"
//            . " https://*.google.com"
//        );
//
//        $this->js[] = 'https://widget.cloudpayments.' . $cloudpayment_domen . '/bundles/cloudpayments';
    }

}//Class